/* Generated by tools/gen_charset.py -- do not edit by hand. */
#ifndef CHARSET_CODES_H
#define CHARSET_CODES_H

#define CH_CORNER_TL 128
#define CH_CORNER_TR 129
#define CH_CORNER_BL 130
#define CH_CORNER_BR 131
#define CH_EDGE_TOP 132
#define CH_EDGE_BOTTOM 133
#define CH_EDGE_LEFT 134
#define CH_EDGE_RIGHT 135
#define CH_SOLID_BLOCK 136
#define CH_CARDBACK 137
#define CH_CURSOR 138
#define CH_ICON_SKIP 139
#define CH_ICON_REVERSE 140
#define CH_ICON_DRAW2 141
#define CH_ICON_WILD 142
#define CH_DIGIT_0 143
#define CH_DIGIT_1 144
#define CH_DIGIT_2 145
#define CH_DIGIT_3 146
#define CH_DIGIT_4 147
#define CH_DIGIT_5 148
#define CH_DIGIT_6 149
#define CH_DIGIT_7 150
#define CH_DIGIT_8 151
#define CH_DIGIT_9 152

#endif
